### ISSUE TITLE
Write-Menu - Problem with PropertyToShow

### ISSUE THREAD

**Issue by sql-aus-hh** [rgel/PowerShell#3]
Property [1] does not exist
At C:\Users\XXXXX\Documents\WindowsPowerShell\Modules\MS-Module\MS-Module.psm1:202 char:90
+ ... ropertyToShow)) { Throw "Property [$PropertyToShow] does not exist" }
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Property [1] does not exist:String) [], RuntimeException
    + FullyQualifiedErrorId : Property [1] does not exist

Here is what I'm doing:
# Getting all Locations where we can provide Azure SQL Databases
$AzureSQLLocations = (Get-AzureRmResourceProvider -ListAvailable | Where-Object {$_.ProviderNamespace -eq 'Microsoft.SQL'} | Select *).Locations
$AzureSQLLocation = Write-Menu -Menu ($AzureSQLLocations) -AddExit 1 -Header 'Azure SQL Database Creation - Location Selection'

$RessourceGroups = Get-AzureRmResourceGroup -Location $AzureSQLLocation

which results into :

Azure SQL Database Creation - Location Selection
[01] Australia East
[02] Australia Southeast
[03] Brazil South
[04] Canada Central
[05] Canada East
[06] Central India
[07] Central US
[08] East Asia
[09] East US

Then I'm selecting "2" pressing "Enter" and then the Error Message appears :-(

Might be ... because of the space within the selection?!?

**Comment by sql-aus-hh** [comment]
Sorry for disturbance... It was my fault... 
The error appears right after selecting the region but it was not that function... it was a step further where the resultset was more than a string :-(

So I changed my code to just return a string... now everything works as expected.

Thanx for that great Menu-Tool!

**Comment by rgel** [comment]
Nothing wrong.
Tomorrow when I come to work, I will send you your code with changes. Of
course it will be example only.
By and large, as best practices it is not recommended to use dot notation
like "().Property". Instead, use " | select Property".
Aftethat use that property name as value for -PropertyToShow parameter in
the menu function.
And more, I always gladly answer questions from my readers.

**Comment by rgel** [comment]
Your code is absolutely operative. Pay attention to '-Prompt' parameter.
$AzureSQLLocation = Write-Menu -Menu ($AzureSQLLocations) -AddExit -Header 'Azure SQL Database Creation' -Prompt 'Select Location'
Happy coding

**Comment by sql-aus-hh** [comment]
Hi,

I’d searched on the wrong line of code… it was not the Location Menu… it was the next step where the problem was…

# Get all RessourceGroups within that Location
$RessourceGroups = Get-AzureRmResourceGroup -Location $AzureSQLLocation

That “Get-AzureRMResourceGroup” returns more than one line (and no line with “name”), so I had to change it to

# Get all RessourceGroups within that Location
$RessourceGroups = (Get-AzureRmResourceGroup -Location $AzureSQLLocation).ResourceGroupName

Now everything works as desired.

Thanks a lot for your support and quick answers.

Best regards
Bjoern

**Comment by rgel** [comment]
NOP
Any question - I'am here
